init commit
EasyMicroservices/Comments-Microservice pull request #1
Opened 2023-07-16 14:39 UTC by ElyasAmini01

2023-07-16 15:33 UTC, Ali-YousefiTelori requested changes

2023-07-16 15:33 UTC, Ali-YousefiTelori commented on .github/workflows/dotnet-linux.yml
> +        run: dotnet restore ./src/CSharp/EasyMicroservices.WhiteLabelsMicroservice.sln
```suggestion
        run: dotnet restore ./src/CSharp/EasyMicroservices.CommentsMicroservice.sln
```

2023-07-16 15:33 UTC, Ali-YousefiTelori commented on .github/workflows/dotnet-linux.yml
> +        run: dotnet build ./src/CSharp/EasyMicroservices.WhiteLabelsMicroservice.sln --no-restore
```suggestion
        run: dotnet build ./src/CSharp/EasyMicroservices.CommentsMicroservice.sln --no-restore
```

2023-07-16 15:33 UTC, Ali-YousefiTelori commented on .github/workflows/dotnet-linux.yml
> +          dotnet test ./src/CSharp/EasyMicroservices.WhiteLabelsMicroservice.sln --no-build --verbosity normal -f netcoreapp3.1
```suggestion
          dotnet test ./src/CSharp/EasyMicroservices.CommentsMicroservice.sln --no-build --verbosity normal -f netcoreapp3.1
```

2023-07-16 15:33 UTC, Ali-YousefiTelori commented on .github/workflows/dotnet-linux.yml
> +          dotnet test ./src/CSharp/EasyMicroservices.WhiteLabelsMicroservice.sln --no-build --verbosity normal -f net6.0
```suggestion
          dotnet test ./src/CSharp/EasyMicroservices.CommentsMicroservice.sln --no-build --verbosity normal -f net6.0
```

2023-07-16 15:33 UTC, Ali-YousefiTelori commented on .github/workflows/dotnet-linux.yml
> +          dotnet test ./src/CSharp/EasyMicroservices.WhiteLabelsMicroservice.sln --no-build --verbosity normal -f net5.0
```suggestion
          dotnet test ./src/CSharp/EasyMicroservices.CommentsMicroservice.sln --no-build --verbosity normal -f net5.0
```

2023-07-16 15:33 UTC, Ali-YousefiTelori commented on .github/workflows/dotnet-macos-client.yml
> +        run: dotnet restore ./src/CSharp/EasyMicroservices.WhiteLabelsMicroservice.Client.sln
```suggestion
        run: dotnet restore ./src/CSharp/EasyMicroservices.CommentsMicroservice.Client.sln
```

2023-07-16 15:33 UTC, Ali-YousefiTelori commented on .github/workflows/dotnet-macos-client.yml
> +        run: dotnet build ./src/CSharp/EasyMicroservices.WhiteLabelsMicroservice.Client.sln --no-restore
```suggestion
        run: dotnet build ./src/CSharp/EasyMicroservices.CommentsMicroservice.Client.sln --no-restore
```

2023-07-16 15:33 UTC, Ali-YousefiTelori commented on .github/workflows/dotnet-macos-client.yml
> +          dotnet test ./src/CSharp/EasyMicroservices.WhiteLabelsMicroservice.Client.sln --no-build --verbosity normal -f netcoreapp3.1
```suggestion
          dotnet test ./src/CSharp/EasyMicroservices.CommentsMicroservice.Client.sln --no-build --verbosity normal -f netcoreapp3.1
```

2023-07-16 15:33 UTC, Ali-YousefiTelori commented on .github/workflows/dotnet-macos-client.yml
> +          dotnet test ./src/CSharp/EasyMicroservices.WhiteLabelsMicroservice.Client.sln --no-build --verbosity normal -f net6.0
```suggestion
          dotnet test ./src/CSharp/EasyMicroservices.CommentsMicroservice.Client.sln --no-build --verbosity normal -f net6.0
```

2023-07-16 15:33 UTC, Ali-YousefiTelori commented on .github/workflows/dotnet-macos-client.yml
> +          dotnet test ./src/CSharp/EasyMicroservices.WhiteLabelsMicroservice.Client.sln --no-build --verbosity normal -f net5.0
```suggestion
          dotnet test ./src/CSharp/EasyMicroservices.CommentsMicroservice.Client.sln --no-build --verbosity normal -f net5.0
```

2023-07-16 15:33 UTC, Ali-YousefiTelori commented on README.md
> +# Tenants-Microservice
```suggestion
# Comments-Microservice
```

2023-07-16 15:42 UTC, mahdidelzendeh72 approved these changes

2023-07-17 15:38 UTC, mahdidelzendeh72 approved these changes

2023-07-17 15:54 UTC, Ali-YousefiTelori requested changes

2023-07-17 15:54 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.CommentsMicroservice.Database/Database/Schemas/CommentSchema.cs
> +        public DateTime CreationTime { get; set; }
Change it to CreationDateTime

2023-07-17 15:54 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.CommentsMicroservice.Database/Database/Schemas/CommentSchema.cs
> +        public DateTime ModifiationTime { get; set; }
Change it to ModifiationDateTime

2023-07-17 15:54 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.CommentsMicroservice.Domain/Contracts/Common/CommentContract.cs
> +        public DateTime CreationTime { get; set; }
Rename creation and modification same as entity

2023-07-17 19:54 UTC, Ali-YousefiTelori approved these changes
Thank you @ElyasAmini01 for your contribution.

2023-07-17 19:54 UTC, merged